export default [
  {
    login: "axy1976",
    id: 52463851,
    node_id: "MDQ6VXNlcjUyNDYzODUx",
    avatar_url: "https://avatars.githubusercontent.com/u/52463851?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/axy1976",
    html_url: "https://github.com/axy1976",
    followers_url: "https://api.github.com/users/axy1976/followers",
    following_url:
      "https://api.github.com/users/axy1976/following{/other_user}",
    gists_url: "https://api.github.com/users/axy1976/gists{/gist_id}",
    starred_url: "https://api.github.com/users/axy1976/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/axy1976/subscriptions",
    organizations_url: "https://api.github.com/users/axy1976/orgs",
    repos_url: "https://api.github.com/users/axy1976/repos",
    events_url: "https://api.github.com/users/axy1976/events{/privacy}",
    received_events_url: "https://api.github.com/users/axy1976/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Hardikkyada",
    id: 81248575,
    node_id: "MDQ6VXNlcjgxMjQ4NTc1",
    avatar_url: "https://avatars.githubusercontent.com/u/81248575?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Hardikkyada",
    html_url: "https://github.com/Hardikkyada",
    followers_url: "https://api.github.com/users/Hardikkyada/followers",
    following_url:
      "https://api.github.com/users/Hardikkyada/following{/other_user}",
    gists_url: "https://api.github.com/users/Hardikkyada/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Hardikkyada/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Hardikkyada/subscriptions",
    organizations_url: "https://api.github.com/users/Hardikkyada/orgs",
    repos_url: "https://api.github.com/users/Hardikkyada/repos",
    events_url: "https://api.github.com/users/Hardikkyada/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Hardikkyada/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "imNK2204",
    id: 81278594,
    node_id: "MDQ6VXNlcjgxMjc4NTk0",
    avatar_url: "https://avatars.githubusercontent.com/u/81278594?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/imNK2204",
    html_url: "https://github.com/imNK2204",
    followers_url: "https://api.github.com/users/imNK2204/followers",
    following_url:
      "https://api.github.com/users/imNK2204/following{/other_user}",
    gists_url: "https://api.github.com/users/imNK2204/gists{/gist_id}",
    starred_url: "https://api.github.com/users/imNK2204/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/imNK2204/subscriptions",
    organizations_url: "https://api.github.com/users/imNK2204/orgs",
    repos_url: "https://api.github.com/users/imNK2204/repos",
    events_url: "https://api.github.com/users/imNK2204/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/imNK2204/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Prithiviraj69",
    id: 85940424,
    node_id: "MDQ6VXNlcjg1OTQwNDI0",
    avatar_url: "https://avatars.githubusercontent.com/u/85940424?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Prithiviraj69",
    html_url: "https://github.com/Prithiviraj69",
    followers_url: "https://api.github.com/users/Prithiviraj69/followers",
    following_url:
      "https://api.github.com/users/Prithiviraj69/following{/other_user}",
    gists_url: "https://api.github.com/users/Prithiviraj69/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Prithiviraj69/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Prithiviraj69/subscriptions",
    organizations_url: "https://api.github.com/users/Prithiviraj69/orgs",
    repos_url: "https://api.github.com/users/Prithiviraj69/repos",
    events_url: "https://api.github.com/users/Prithiviraj69/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Prithiviraj69/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "IMandarWagh",
    id: 96492021,
    node_id: "U_kgDOBcBZ9Q",
    avatar_url: "https://avatars.githubusercontent.com/u/96492021?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/IMandarWagh",
    html_url: "https://github.com/IMandarWagh",
    followers_url: "https://api.github.com/users/IMandarWagh/followers",
    following_url:
      "https://api.github.com/users/IMandarWagh/following{/other_user}",
    gists_url: "https://api.github.com/users/IMandarWagh/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/IMandarWagh/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/IMandarWagh/subscriptions",
    organizations_url: "https://api.github.com/users/IMandarWagh/orgs",
    repos_url: "https://api.github.com/users/IMandarWagh/repos",
    events_url: "https://api.github.com/users/IMandarWagh/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/IMandarWagh/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ShraddhaDudhat",
    id: 96579828,
    node_id: "U_kgDOBcGw9A",
    avatar_url: "https://avatars.githubusercontent.com/u/96579828?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ShraddhaDudhat",
    html_url: "https://github.com/ShraddhaDudhat",
    followers_url: "https://api.github.com/users/ShraddhaDudhat/followers",
    following_url:
      "https://api.github.com/users/ShraddhaDudhat/following{/other_user}",
    gists_url: "https://api.github.com/users/ShraddhaDudhat/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ShraddhaDudhat/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ShraddhaDudhat/subscriptions",
    organizations_url: "https://api.github.com/users/ShraddhaDudhat/orgs",
    repos_url: "https://api.github.com/users/ShraddhaDudhat/repos",
    events_url: "https://api.github.com/users/ShraddhaDudhat/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ShraddhaDudhat/received_events",
    type: "User",
    site_admin: false,
  },
];
